# Generated by Django 3.0.2 on 2020-01-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.CharField(max_length=5000)),
                ('category', models.CharField(max_length=50, null=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('authorname', models.CharField(default='', max_length=200)),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
